# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $entityManager: "@doctrine.orm.default_entity_manager"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    MarcusSports\:
        resource: '../src/'
        exclude:
            - '../src/**/Domain/'

    MarcusSports\Shared\Infrastructure\Command\DbInitCommand:
        tags: [ 'console.command' ]

    MarcusSports\Shared\Infrastructure\Command\DbTestCleanCommand:
        tags: [ 'console.command' ]
        arguments:
            $environment: '%kernel.environment%'

    MarcusSports\Users\User\Infrastructure\Controller\:
        resource: '../src/Users/User/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'

    MarcusSports\Users\Auth\Infrastructure\Controller\:
        resource: '../src/Users/Auth/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'

    MarcusSports\Catalog\Product\Infrastructure\Controller\:
        resource: '../src/Catalog/Product/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'

    MarcusSports\Catalog\PartType\Infrastructure\Controller\:
        resource: '../src/Catalog/PartType/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'

    MarcusSports\Catalog\PartItem\Infrastructure\Controller\:
        resource: '../src/Catalog/PartItem/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'

    MarcusSports\Catalog\CompatibilityRule\Infrastructure\Controller\:
        resource: '../src/Catalog/CompatibilityRule/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'

    MarcusSports\Catalog\PriceModifier\Infrastructure\Controller\:
        resource: '../src/Catalog/PriceModifier/Infrastructure/Controller'
        tags:
            - 'controller.service_arguments'


    MarcusSports\Users\Auth\Infrastructure\JWTTokenGenerator:
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'

    MarcusSports\Users\Auth\Infrastructure\Provider\BearerUserProvider:
        arguments:
            - '@MarcusSports\Users\User\Domain\Repository\UserRepository'

#    MarcusSports\Laravel\User\Infrastructure\:
#        resource: '../src/Laravel/User/Infrastructure/'
#        tags:
#            - 'controller.service_arguments'
#            - { name: 'monolog.logger', channel: 'domain_events' }

    MarcusSports\Users\User\Domain\Repository\UserRepository: '@MarcusSports\Users\User\Infrastructure\Persistence\UserRepositoryDoctrineMysql'
    MarcusSports\Catalog\Product\Domain\Repository\ProductRepository: '@MarcusSports\Catalog\Product\Infrastructure\Persistence\ProductRepositoryDoctrineMysql'
    MarcusSports\Catalog\PartType\Domain\Repository\PartTypeRepository: '@MarcusSports\Catalog\PartType\Infrastructure\Persistence\PartTypeRepositoryDoctrineMysql'
    MarcusSports\Catalog\PartItem\Domain\Repository\PartItemRepository: '@MarcusSports\Catalog\PartItem\Infrastructure\Persistence\PartItemRepositoryDoctrineMysql'
    MarcusSports\Catalog\CompatibilityRule\Domain\Repository\CompatibilityRuleRepository: '@MarcusSports\Catalog\CompatibilityRule\Infrastructure\Persistence\CompatibilityRuleRepositoryDoctrineMysql'
    MarcusSports\Catalog\PriceModifier\Domain\Repository\PriceModifierRepository: '@MarcusSports\Catalog\PriceModifier\Infrastructure\Persistence\PriceModifierRepositoryDoctrineMysql'
