doctrine:
  dbal:
    default_connection: 'default'
    types:
      user_uuid: MarcusSports\Users\User\Infrastructure\Persistence\Doctrine\UserUuidType
      user_role: MarcusSports\Users\User\Infrastructure\Persistence\Doctrine\UserRoleType
      product_uuid: MarcusSports\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductUuidType
      product_base_price: MarcusSports\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductPriceType
      product_category: MarcusSports\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductCategoryType
      part_type_uuid: MarcusSports\Catalog\PartType\Infrastructure\Persistence\Doctrine\PartTypeUuidType
      part_item_uuid: MarcusSports\Catalog\PartItem\Infrastructure\Persistence\Doctrine\PartItemUuidType
      part_item_status: MarcusSports\Catalog\PartItem\Infrastructure\Persistence\Doctrine\PartItemStatusType
      part_item_price: MarcusSports\Catalog\PartItem\Infrastructure\Persistence\Doctrine\PartItemPriceType
      compatibility_rule_uuid: MarcusSports\Catalog\CompatibilityRule\Infrastructure\Persistence\Doctrine\CompatibilityRuleUuidType
      price_modifier_uuid: MarcusSports\Catalog\PriceModifier\Infrastructure\Persistence\Doctrine\PriceModifierUuidType
      price_modifier_scope: MarcusSports\Catalog\PriceModifier\Infrastructure\Persistence\Doctrine\PriceModifierScopeType
      price_modifier_adjustment: MarcusSports\Catalog\PriceModifier\Infrastructure\Persistence\Doctrine\PriceModifierAdjustmentType
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: true
    controller_resolver:
      auto_mapping: false
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            user_domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/mapping/User'
                prefix: 'MarcusSports\Users\User\Domain'
                alias: user_domain
            product_domain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/config/orm/mapping/Product'
              prefix: 'MarcusSports\Catalog\Product\Domain'
              alias: product_domain
            part_type_domain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/config/orm/mapping/PartType'
              prefix: 'MarcusSports\Catalog\PartType\Domain'
              alias: part_type_domain
            part_item_domain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/config/orm/mapping/PartItem'
              prefix: 'MarcusSports\Catalog\PartItem\Domain'
              alias: part_item_domain
            compatibility_rule_domain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/config/orm/mapping/CompatibilityRule'
              prefix: 'MarcusSports\Catalog\CompatibilityRule\Domain'
              alias: compatibility_rule_domain
            price_modifier:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/config/orm/mapping/PriceModifier'
              prefix: 'MarcusSports\Catalog\PriceModifier\Domain'
              alias: price_modifier
#      other-entity-manager:
#        connection: other-entity-manager
#        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        mappings:
#          other-entity-manager_user_domain:
#            is_bundle: false
#            type: xml
#            dir: '%kernel.project_dir%/config/orm/mapping_other_entity_manager/User'
#            prefix: 'MarcusSports\OtherFolder\User\Domain'
#            alias: other_entity_manager_user_domain

when@test:
  doctrine:
    dbal:
      connections:
        default:
          url: '%env(resolve:DATABASE_URL_TEST)%'
      # "TEST_TOKEN" is typically set by ParaTest
#      dbname_suffix: 'Test%env(default::TEST_TOKEN)%'