compatibility_rule_post:
  path: /compatibility-rule
  controller: MarcusSports\Catalog\CompatibilityRule\Infrastructure\Controller\CompatibilityRulePostController
  methods: [POST]

compatibility_rule_get:
  path: /compatibility-rule
  controller: MarcusSports\Catalog\CompatibilityRule\Infrastructure\Controller\CompatibilityRuleGetController
  methods: [GET]